### ISSUE TITLE
Help me get this working for $20

### ISSUE THREAD

**Issue by Brodys** [ThaisenPM/Loader1#13]
Help me get this working ill give you $20 via paypal, i just want a decent working loader for a community hack site. I want every feature working properly which 90% of them already are for me, just have a few hickups. I know this is old but out of the loaders you've uploaded, this one fits me needs the most. I'll do some heavy GUI modifications and could send them to you also if you'd like.

**Comment by Brodys** [comment]
EDIT: $20 if you do a few additions, and $10 if you just keep it how it is and just fix what's wrong/getting everything working for me

**Comment by Brodys** [comment]
I got everything working, usergroups everything, even added so they need to verify email before using the client. But i cannot seem to make it so it'll download the dll from my webserver, it just downloads aboyt 841 bytes then stops.

**Comment by Brodys** [comment]
fixed that issue also, it was my webhost, the injector is broken like you stated, you said you changed something to break it? i cannot find what you broke, i found the exact source you used for the injector and re implemented it and no luck..

**Comment by ThaisenPM** [comment]
Don't use this loader... That will be $20
